version: 2.1

executors:
  docker:
    parameters:
      py-version:
        default: "3.7"
        type: string
    docker:
      - image: circleci/python:<< parameters.py-version >>

commands:
  custom-command:
    parameters:
      py-version:
        default: "3.7"
        type: string    
    steps:
      - restore_cache:
          key: cache-<< parameters.py-version >>
      - run:
          command: |
            mkdir -p test
            [[ ! -f test/bla ]] && echo bla > test/bla || true
      - save_cache:
          key: cache-<< parameters.py-version >>
          paths:
            - "~/test"


jobs:
  job-1:
    parameters:
      py-version:
        default: "3.7"
        type: string    
    executor:
      name: docker
      py-version: << parameters.py-version >>
    steps:
      - custom-command

workflows:
  wf1:
    jobs:
      - job-1:
          name: job-1-3.6
          py-version: "3.6"
      - job-1:
          name: job-1-3.7
          py-version: "3.7"
