jobs:
  s1:
    docker:
      - image: circleci/python:3.6
    steps:
      run:
        command: |
          mkdir t
          echo x > t/x
      persist_to_workspace:
        root: "."
        paths:
          - t

  s2:
    docker:
      - image: circleci/python:3.6
    steps:
      - attach_workspace:
          at: "."
      - run:
          command: tree; ls -la . t
      - run:
          command: echo y > y; ls -la .
