version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.6


jobs:
  pre:
    executor:
      name: default
    steps:
      - run:
          command: |
            mkdir bla
            echo pre > ${CIRCLE_JOB}.txt
      - persist_to_workspace:
          root: "~"
          paths:
            - bla
  test:
    executor:
      name: default
    steps:
      - attach_workspace:
        at: ~
      - run:
          command: |
            mkdir bla
            echo pre > ${CIRCLE_JOB}.txt
            ls -la bla
      - persist_to_workspace:
          root: "~"
          paths:
            - bla

  finalize:
    executor:
      name: default
    steps:
      - attach_workspace:
        at: ~
      - run:
          command: |
            ls -la bla

workflows:
  bla:
    jobs:
      - pre
      - test:
          name: test-a
          requires:
            - pre
      - test:
          name: test-b
          requires:
            - pre
      - finalize:
          requires:
            - test-a
            - test-b
