version: 2

tpl: &tpl
  docker:
    - image: circleci/python:3.6
  steps:
    - run:
        command: |
          sleep 10
          echo done 

jobs:
  prepare-a:
    <<: *tpl
  prepare-b:
    <<: *tpl
  test-a-1:
    <<: *tpl
  test-b-1:
    <<: *tpl
  test-a-2:
    <<: *tpl
  test-b-2:
    <<: *tpl
  test-a-3:
    <<: *tpl
  test-b-3:
    <<: *tpl
  finalize:
    <<: *tpl

workflows:
  version: 2
  bla:
    jobs:
      - prepare-a
      - prepare-b
      - test-a-1:
          requires: 
            - prepare-a
      - test-b-1:
          requires: 
            - prepare-b
      - test-a-2:
          requires: 
            - prepare-a
      - test-b-2:
          requires: 
            - prepare-b
      - test-a-3:
          requires: 
            - prepare-a
      - test-b-3:
          requires: 
            - prepare-b
      - finalize:
          requires:
            - test-a-1
            - test-a-2
            - test-a-3
            - test-b-1
            - test-b-2
            - test-b-3
