version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.6


jobs:
  pre:
    executor:
      name: default
    steps:
      - run:
          command: |
            pwd
            mkdir -p bla
            echo pre > bla/${CIRCLE_JOB}.txt
      - persist_to_workspace:
          root: "~"
          paths:
            - project/bla
  doit:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: "~"
      - run:
          command: |
            mkdir -p bla
            rm -rf bla/*
            echo pre > bla/${CIRCLE_JOB}.txt
            ls -la bla
      - persist_to_workspace:
          root: "~"
          paths:
            - project/bla

  finalize:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: "~"
      - run:
          command: |
            ls -la bla

workflows:
  bla:
    jobs:
      - pre
      - doit:
          name: doit-a
          requires:
            - pre
      - doit:
          name: doit-b
          requires:
            - pre
      - finalize:
          requires:
            - doit-a
            - doit-b
